spring:
  application:
    name: blog_web
  datasource:
    driver-class-name:
    url:
    username:
    password:
  config:
    import:
      - classpath:application-jwt.yaml
      - classpath:application-minio.yaml
      - classpath:application-db.yaml

##sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt密钥
jwt:
  secretKey:
minio:
  endpoint:
  bucketName:
  accessKey:
  secretKey:
